ConnectionStrings:
  Postgres: Server=localhost;Port=5432;Database=db_invoice;User Id=postgres;Password=Aforo255#2019;
  Mysql: server=localhost;port=3306;database=db_operation;user=root;password=Aforo255#2019
  SqlServer: Server=localhost,1433;Database=db_security;User Id=sa;Password=Aforo255#2019;

MongoDbSettings:
  ConnectionString: mongodb://localhost:27017
  Database: db_transaction

Rabbitmq:
  Hostname: localhost
  Username: guest
  Password: guest
  VirtualHost: "/"
  Port: '5672'
  
BearerToken:
  Enabled: true
  Issuer: http://mdmg92
  Audience: web
  Key: CLave#12548MIentrasMas45566Mejor____%%%dddd
  Expiration: '30'

environment: production
