ConnectionStrings.Postgres: Server=localhost;Port=5432;Database=db_invoice;User Id=postgres;Password=Aforo255#2019;

ConnectionStrings.Mysql: server=localhost;port=3306;database=db_operation;user=root;password=Aforo255#2019

MongoDbSettings:
  ConnectionString: mongodb://localhost:27018
  Database: db_transaction

Rabbitmq:
  Hostname: localhost
  Username: guest
  Password: guest
  VirtualHost: "/"
  Port: '5672'

environment: production
